### ISSUE TITLE
With release 1.10.3 we observed our jenkins pipelines are failing with following error "AttributeError: 'NoneType' object has no attribute 'version_configs'"

### ISSUE THREAD

**Issue by vamsi-l** [GoogleCloudPlatform/dfcx-scrapi#173]
Jenkins builds which copies latest versions from lab to higher environments are failing post 1.10.3 release with following error

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/AgentName/scrapi/copy_agent_env_versions.py", line 65, in <module>
    envs.update_environment(to_env_id, version_configs=new_env_version_configs)
  File "/usr/local/lib/python3.9/site-packages/dfcx_scrapi/core/scrapi_base.py", line 452, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dfcx_scrapi/core/environments.py", line 315, in update_environment
    mask = self._update_kwargs(environment_obj, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dfcx_scrapi/core/scrapi_base.py", line 406, in _update_kwargs
    setattr(obj, key, value)
AttributeError: 'NoneType' object has no attribute 'version_configs' 

## Expected Behavior
With 1.10.2 release we are not facing any issue so we need your help in fixing this issue

## Current Behavior
When try to run build to copy new versions of flows to higher environment we are noticing following error

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/AgentName/scrapi/copy_agent_env_versions.py", line 65, in <module>
    envs.update_environment(to_env_id, version_configs=new_env_version_configs)
  File "/usr/local/lib/python3.9/site-packages/dfcx_scrapi/core/scrapi_base.py", line 452, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dfcx_scrapi/core/environments.py", line 315, in update_environment
    mask = self._update_kwargs(environment_obj, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dfcx_scrapi/core/scrapi_base.py", line 406, in _update_kwargs
    setattr(obj, key, value)
AttributeError: 'NoneType' object has no attribute 'version_configs' 

## Possible Solution

For now we are using 1.10.2 release version which is working fine but we need your help in fixing this issue

You can find the following changelog https://github.com/GoogleCloudPlatform/dfcx-scrapi/compare/1.10.2...1.10.3 which you can review to fix this issue in the latest release. Please let me know if you need more information on this

**Comment by kmaphoenix** [comment]
@vamsi-l this should be fully resolved with the latest release.  
https://github.com/GoogleCloudPlatform/dfcx-scrapi/releases/tag/1.10.5

Please let us know if this is still causing issues.
